/**
 * Main → Renderer 的**推送**消息大 union(`MainToRendererMessage`)。
 *
 * 从 `ipc.ts` 按域拆出(见该文件头)。各成员接口可能定义在对应的域文件里 —
 * 这里只负责把它们合成一个渲染端监听的判别 union。新增一条推送:先在域文件
 * 定义 payload,再回到这里加进 union。
 */

import type { RuntimeEvent } from "../runtime.js";
import type { LspLanguageId } from "./lsp.js";
import type { RelayStatus } from "../relay.js";
import type { ThemeChangedMessage } from "../theme.js";
import type { UpdateAvailableMessage, UpdateDownloadProgressMessage, UpdateDownloadedMessage } from "./app.js";
import type { RuntimeEventMessage, ToolchainEventMessage } from "./runtimes.js";
import type { LibraryChangedMessage, WorkflowChangedMessage, ComposerAttachMessage } from "./library.js";

/* ──────────────────────────  Main → Renderer (events)  ─────────────────────── */

export interface ClaudeEventMessage {
  channel: "claude:event";
  sessionId: string;
  event: RuntimeEvent;
}

/**
 * Pushed from main to renderer when an auto-generated session title has been
 * written to the DB by the background title-gen routine. The renderer patches
 * its in-memory session lists so the sidebar / tabs reflect the new title
 * without a full reload. Mirrors the rename flow but is main-initiated.
 */
export interface SessionTitleUpdatedMessage {
  channel: "session:titleUpdated";
  sessionId: string;
  title: string;
}

export interface TerminalDataMessage {
  channel: "terminal:data";
  terminalId: string;
  data: string;
}

/** Fired when a PTY process exits (user typed `exit`, shell crashed, or kill). */
export interface TerminalExitMessage {
  channel: "terminal:exit";
  terminalId: string;
  /** Process exit code, or null if killed by signal / unknown. */
  exitCode: number | null;
}

/** Pushed from main -> renderer for LSP diagnostics, server logs, and running
 *  state changes. The `payload` shape depends on `type`:
 *  - "diagnostics":  { uri: string; diagnostics: LspDiagnostic[] }
 *  - "log":          { level: "info" | "warn" | "error"; message: string }
 *  - "stateChanged": { running: boolean }
 *  Kept as `unknown` here so the contract stays decoupled from the renderer's
 *  narrowing logic. */
export interface LspEventMessage {
  channel: "lsp:event";
  workspacePath: string;
  language: LspLanguageId;
  /** Type-specific shape: diagnostics → LspDiagnostic[], log →
   *  { level, message }, stateChanged → LspStateChangedPayload. */
  type: "diagnostics" | "log" | "stateChanged";
  payload: unknown;
}

/** A DOM element picked by the user from the embedded browser. This is the
 *  payload produced by the picker script injected into a page's main world,
 *  forwarded to the renderer where it becomes a `ContentTag` (kind="element")
 *  in the composer. */
export interface PickedElement {
  /** CSS selector path generated by the picker (id > class chain > nth-child). */
  selector: string;
  /** The element's outerHTML, truncated to a sane cap (≤ 2000 chars) so a huge
   *  subtree can't blow up the prompt. */
  outerHTML: string;
  /** The page URL the element was picked from. */
  url: string;
  /** Short single-line preview for the composer chip (e.g. `button.btn`). */
  preview: string;
}

/** Pushed from main -> renderer for the embedded browser panel. The payload
 *  shape depends on `type`:
 *  - "navigation": the active page changed (URL/title/back/forward state).
 *  - "loading":    the page started or stopped loading.
 *  - "pickResult": the user clicked an element in pick mode.
 *  - "crashed":    the renderer process died; the view needs recreating.
 *  - "agentOpened": an agent tool created/reused a browser view; the renderer
 *    should switch the right panel to the browser tab so the view is visible.
 *  - "tabOpened": a page opened a link in a new window (target=_blank /
 *    window.open); main created a fresh view for it and the renderer should
 *    adopt that browserId as a new panel tab (payload: BrowserTabOpened).
 *  - "authRequest": a page asked for HTTP Basic Auth; the payload is a
 *    BrowserAuthRequest and the renderer should show a login dialog, then
 *    answer via the browser.authRespond RPC.
 *  - "download": the embedded browser started/finished a file download
 *    (payload: BrowserDownloadProgress); the renderer currently only logs it —
 *    the agent reads state via the browser_downloads tool. */
export interface BrowserEventMessage {
  channel: "browser:event";
  browserId: string;
  type:
    | "navigation"
    | "loading"
    | "pickResult"
    | "crashed"
    | "agentOpened"
    | "tabOpened"
    | "authRequest"
    | "download";
  payload: unknown;
}

/** Payload of the "download" browser push event. Emitted when a download
 *  starts and again when it reaches a terminal state (completed / cancelled /
 *  interrupted); progress ticks are intentionally not pushed (the agent polls
 *  browser_downloads instead). `path` is where the file is being written. */
export interface BrowserDownloadProgress {
  downloadId: string;
  filename: string;
  path: string;
  url: string;
  state: "progressing" | "completed" | "cancelled" | "interrupted";
  receivedBytes: number;
  totalBytes: number;
}

/** Payload of the "tabOpened" browser push event. `background` is true when
 *  the link was opened behind the current tab (middle/ctrl-click); the
 *  renderer adds the tab without switching to it in that case. */
export interface BrowserTabOpened {
  url: string;
  title?: string;
  background?: boolean;
}

/** Payload of the "authRequest" browser push event. The requestId maps 1:1 to
 *  a pending Electron login callback held in main; answering (or cancelling)
 *  with browser.authRespond resolves it. */
export interface BrowserAuthRequest {
  requestId: string;
  /** Origin the credentials will be sent to (scheme://host[:port]). */
  origin: string;
  /** Host name only, for the dialog title. */
  host: string;
}

/**
 * Pushed from main -> renderer whenever the main window gains or loses focus.
 * The renderer uses this as the basis for notification decisions: when the
 * window is unfocused (minimized or another app is frontmost), background
 * session events warrant a stronger notification (OS notification); when
 * focused, only in-app toasts / badges are needed.
 */
export interface WindowFocusChangedMessage {
  channel: "window:focusChanged";
  /** True when the main window is focused (frontmost + not minimized). */
  focused: boolean;
}

/**
 * Pushed from main -> renderer when the user clicks an OS notification. The
 * main process has already shown + focused the window; this event tells the
 * renderer which session to navigate to (selectSession / openTab) so the user
 * lands directly on the thread that generated the notification.
 */
export interface NotificationFocusSessionMessage {
  channel: "notification:focusSession";
  sessionId: string;
}

/** Pushed from main → renderer on relay state changes (connecting, deployed,
 *  connected, error, disconnected). The renderer uses these to update the
 *  remote-access panel without polling. */
export interface RelayEventMessage {
  channel: "relay:event";
  status: RelayStatus;
}

/** Pushed from main → renderer with live ASR results for a voice-input
 *  session. `partial` = interim streaming text (may still change), `final` =
 *  a committed segment for the session. The renderer matches results to its
 *  composer via `sessionId` (the per-listen token it chose at voice.start). */
export interface VoiceResultMessage {
  channel: "voice:result";
  sessionId: string;
  kind: "partial" | "final";
  text: string;
}

/** Pushed from main → renderer while a voice model downloads. The settings
 *  panel renders a progress bar from this; `stage: "done"` means the model is
 *  ready to select. */
export interface VoiceDownloadProgressMessage {
  channel: "voice:downloadProgress";
  modelId: string;
  stage: "downloading" | "done" | "error" | "cancelled";
  percent: number;
  fileIndex: number;
  fileCount: number;
  fileBytes: number;
  error?: string;
}

export type MainToRendererMessage =
  | ClaudeEventMessage
  | SessionTitleUpdatedMessage
  | TerminalDataMessage
  | TerminalExitMessage
  | LspEventMessage
  | BrowserEventMessage
  | ThemeChangedMessage
  | UpdateAvailableMessage
  | UpdateDownloadProgressMessage
  | UpdateDownloadedMessage
  | WindowFocusChangedMessage
  | NotificationFocusSessionMessage
  | RelayEventMessage
  | VoiceResultMessage
  | VoiceDownloadProgressMessage
  | RuntimeEventMessage
  | ToolchainEventMessage
  | LibraryChangedMessage
  | WorkflowChangedMessage
  | ComposerAttachMessage;

