import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { readdirSync, writeFileSync, mkdirSync, mkdtempSync, copyFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
const source=dirname(fileURLToPath(import.meta.url));
const desktop=resolve(source,'../..');
mkdirSync(join(desktop,'.tmp'),{recursive:true});
const dir=mkdtempSync(join(desktop,'.tmp','editor-market-'));
const pnpm=join(desktop,'../../node_modules/.pnpm');
const pkg=(prefix,sub)=>{const name=readdirSync(pnpm).filter(n=>n.startsWith(prefix)).sort().at(-1);if(!name)throw new Error('Missing installed dependency: '+prefix);return join(pnpm,name,'node_modules',sub);};
const esbuild=await import(pathToFileURL(pkg('esbuild@','esbuild/lib/main.js')).href);
const common={bundle:true,tsconfig:join(desktop,'tsconfig.json'),absWorkingDir:desktop,logLevel:'error'};
await esbuild.build({...common,entryPoints:[join(source,'main.ts')],platform:'node',format:'cjs',outfile:join(dir,'checks.cjs')});
const unit=spawnSync(process.execPath,[join(dir,'checks.cjs')],{cwd:desktop,stdio:'inherit',timeout:60000});
if(unit.status!==0)throw new Error('Editor/market regression failed');
await esbuild.build({...common,entryPoints:[join(source,'browser.ts')],platform:'node',format:'cjs',external:['electron'],outfile:join(dir,'browser.cjs')});
await esbuild.build({...common,entryPoints:[join(source,'renderer.tsx')],platform:'browser',format:'iife',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},outfile:join(dir,'bundle.js'),plugins:[{name:'isolated-api',setup(build){build.onResolve({filter:/^@renderer\/lib\/api\.js$/},()=>({path:join(source,'api-stub.ts')}));}}]});
writeFileSync(join(dir,'index.html'),`<!doctype html><meta charset="UTF-8"><div id="market-root"></div><script>window.inlineRan=true</script><script src="bundle.js"></script>`);
writeFileSync(join(dir,'preload.cjs'),`const {contextBridge,ipcRenderer}=require('electron');contextBridge.exposeInMainWorld('fixture',{result:r=>ipcRenderer.send('fixture:result',r)});`);
const electron=(await import(pathToFileURL(pkg('electron@','electron/index.js')).href)).default;
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
console.log('Isolated Electron CSP/progress fixture: '+dir);
const browser=spawnSync(electron,[join(dir,'browser.cjs')],{cwd:dir,stdio:'inherit',env,timeout:45000});
if(browser.status!==0)throw new Error('Electron CSP/progress regression failed');
console.log('PASS editor-market-smoke (fixture only; not production document save E2E)');
