import { useEffect, useMemo, useState } from "react";
import {
  TITLE_GEN_BUILTIN_ALIASES,
  TITLE_GEN_BUILTIN_MODEL_PREFIX,
  TITLE_GEN_MAX_LEN_DEFAULT,
  TITLE_GEN_MAX_LEN_MAX,
  TITLE_GEN_MAX_LEN_MIN,
  TitleGenLangSchema,
  UI_TITLE_GEN_LANG_SETTING_KEY,
  UI_TITLE_GEN_MAX_LEN_SETTING_KEY,
  UI_TITLE_GEN_PROMPT_SETTING_KEY,
  parseTitleGenMaxLen,
  type TitleGenLang,
} from "@contracts/ipc";
import { api } from "@renderer/lib/api.js";
import { useSessionStore } from "@renderer/stores/sessionStore.js";
import { cn } from "@renderer/lib/cn.js";
import { useI18n } from "@renderer/lib/i18n/index.js";
import { Input, Select, Switch } from "@renderer/components/ui/index.js";
import { IconRobot } from "@renderer/lib/icons.js";
import { SettingRow } from "./SettingRow.js";
import { SettingsSection } from "./SettingsSection.js";

/**
 * Thread-title generation settings.
 *
 * Two controls:
 *  - **Auto generate** (toggle): when on, the main process fires a one-shot
 *    LLM call on a session's first user message to produce a short Chinese
 *    title, overwriting the default placeholder. When off, the placeholder
 *    (first 40 chars of the prompt) is kept.
 *  - **Generation model**: pick a SPECIFIC model (supplier + model id).
 *    Only custom-model configs with at least one model are listed; the
 *    user must have configured models first. There is no default model —
 *    until one is picked, titles are not generated.
 *
 * The model value is stored as `"configId:modelId"` in the settings table,
 * same shape as the commit-gen / conflict-resolve model selectors.
 *
 * Renders as its own SettingsSection (card) so it slots into GeneralPanel as
 * a sibling section.
 */
export function TitleGenPanel() {
  const { t } = useI18n();
  const titleGenEnabled = useSessionStore((s) => s.titleGenEnabled);
  const titleGenModel = useSessionStore((s) => s.titleGenModel);
  const setTitleGenEnabled = useSessionStore((s) => s.setTitleGenEnabled);
  const setTitleGenModel = useSessionStore((s) => s.setTitleGenModel);
  const customModels = useSessionStore((s) => s.customModels);

  // Build a flat list of selectable models: one entry per (config, model).
  // Each entry's value is `"configId:modelId"`, label is `"供应商名 -> 模型id"`.
  const modelOptions = useMemo(() => {
    // 内置 Claude(本机 Claude Code 登录)排在最前 —— 没配自定义模型也能用。
    const opts: { value: string; label: string }[] = [
      { value: TITLE_GEN_BUILTIN_MODEL_PREFIX, label: t("settings.titleGen.builtinDefault") },
      ...TITLE_GEN_BUILTIN_ALIASES.map((a) => ({
        value: `${TITLE_GEN_BUILTIN_MODEL_PREFIX}:${a}`,
        label: `Claude Code -> ${a}`,
      })),
    ];
    for (const cfg of customModels) {
      for (const entry of cfg.models) {
        if (entry.id.trim()) {
          opts.push({
            value: `${cfg.id}:${entry.id}`,
            label: `${cfg.name} -> ${entry.id}`,
          });
        }
      }
    }
    return opts;
  }, [customModels, t]);

  // 语言 / 长度 / 风格偏好:直接读写设置表(主进程生成时现读),不进 sessionStore。
  const [lang, setLang] = useState<TitleGenLang>("auto");
  const [maxLenText, setMaxLenText] = useState(String(TITLE_GEN_MAX_LEN_DEFAULT));
  const [stylePrompt, setStylePrompt] = useState("");
  const [savedStyle, setSavedStyle] = useState("");
  useEffect(() => {
    let alive = true;
    void api.setting
      .getMany({ keys: [UI_TITLE_GEN_LANG_SETTING_KEY, UI_TITLE_GEN_MAX_LEN_SETTING_KEY, UI_TITLE_GEN_PROMPT_SETTING_KEY] })
      .then((r) => {
        if (!alive) return;
        const l = TitleGenLangSchema.safeParse(r[UI_TITLE_GEN_LANG_SETTING_KEY] ?? "auto");
        setLang(l.success ? l.data : "auto");
        setMaxLenText(String(parseTitleGenMaxLen(r[UI_TITLE_GEN_MAX_LEN_SETTING_KEY])));
        const sp = r[UI_TITLE_GEN_PROMPT_SETTING_KEY] ?? "";
        setStylePrompt(sp);
        setSavedStyle(sp);
      })
      .catch((err: unknown) => console.error("titleGen settings load failed:", err));
    return () => {
      alive = false;
    };
  }, []);
  const saveSetting = (key: string, value: string) => {
    void api.setting.set({ key, value }).catch((err: unknown) => console.error(`setting.set(${key}) failed:`, err));
  };
  const commitMaxLen = () => {
    const n = parseTitleGenMaxLen(maxLenText);
    setMaxLenText(String(n));
    saveSetting(UI_TITLE_GEN_MAX_LEN_SETTING_KEY, String(n));
  };
  const commitStyle = (v: string) => {
    if (v === savedStyle) return;
    setSavedStyle(v);
    saveSetting(UI_TITLE_GEN_PROMPT_SETTING_KEY, v);
  };
  const langLabel = (l: TitleGenLang) => t(`settings.titleGen.lang.${l}`);

  return (
    <SettingsSection
      title={t("settings.titleGen.sectionTitle")}
      desc={t("settings.titleGen.sectionDesc")}
    >
      {/* Auto-generate toggle */}
      <SettingRow
        title={t("settings.titleGen.autoGenerate")}
        desc={t("settings.titleGen.autoGenerateDesc")}
        htmlFor="setting-titlegen-enabled"
      >
        <Switch
          id="setting-titlegen-enabled"
          checked={titleGenEnabled}
          onCheckedChange={setTitleGenEnabled}
          label={titleGenEnabled ? t("settings.on") : t("settings.off")}
        />
      </SettingRow>

      {/* Model selector - specific supplier + role binding */}
      <SettingRow
        title={t("settings.genModel")}
        desc={t("settings.titleGen.genModelDesc")}
      >
        {modelOptions.length > 0 ? (
          <Select.Root
            value={titleGenModel}
            onValueChange={(v) => setTitleGenModel((v as string) ?? null)}
          >
            <Select.Trigger
              disabled={!titleGenEnabled}
              className={cn("w-full", !titleGenEnabled && "cursor-not-allowed opacity-50")}
            >
              <Select.Value>
                {(val: string | null) => (
                  <span
                    className={cn(
                      "flex min-w-0 items-center gap-1.5",
                      !val && "text-content-subtle",
                    )}
                  >
                    <IconRobot size={14} className="text-content-muted" />
                    <span className="truncate">
                      {val
                        ? (modelOptions.find((o) => o.value === val)?.label ?? val)
                        : t("settings.titleGen.modelPlaceholder")}
                    </span>
                  </span>
                )}
              </Select.Value>
            </Select.Trigger>
            <Select.Portal>
              <Select.Positioner>
                <Select.Popup>
                  <Select.List>
                    {modelOptions.map((opt) => (
                      <Select.Item key={opt.value} value={opt.value}>
                        <IconRobot size={14} className="text-content-muted" />
                        <Select.ItemText>{opt.label}</Select.ItemText>
                      </Select.Item>
                    ))}
                  </Select.List>
                </Select.Popup>
              </Select.Positioner>
            </Select.Portal>
          </Select.Root>
        ) : (
          <p className={cn("text-[0.7857em] text-content-subtle", !titleGenEnabled && "opacity-50")}>
            {t("settings.titleGen.noModelsHint")}
          </p>
        )}
      </SettingRow>

      <SettingRow title={t("settings.titleGen.langTitle")} desc={t("settings.titleGen.langDesc")}>
        <Select.Root
          value={lang}
          onValueChange={(v) => {
            const parsed = TitleGenLangSchema.safeParse(v);
            if (!parsed.success) return;
            setLang(parsed.data);
            saveSetting(UI_TITLE_GEN_LANG_SETTING_KEY, parsed.data);
          }}
        >
          <Select.Trigger
            disabled={!titleGenEnabled}
            className={cn("w-full", !titleGenEnabled && "cursor-not-allowed opacity-50")}
          >
            <Select.Value>{(val: TitleGenLang) => langLabel(val)}</Select.Value>
          </Select.Trigger>
          <Select.Portal>
            <Select.Positioner>
              <Select.Popup>
                <Select.List>
                  {TitleGenLangSchema.options.map((l) => (
                    <Select.Item key={l} value={l}>
                      <Select.ItemText>{langLabel(l)}</Select.ItemText>
                    </Select.Item>
                  ))}
                </Select.List>
              </Select.Popup>
            </Select.Positioner>
          </Select.Portal>
        </Select.Root>
      </SettingRow>

      <SettingRow
        title={t("settings.titleGen.maxLenTitle")}
        desc={t("settings.titleGen.maxLenDesc", { min: TITLE_GEN_MAX_LEN_MIN, max: TITLE_GEN_MAX_LEN_MAX })}
      >
        <Input
          type="number"
          min={TITLE_GEN_MAX_LEN_MIN}
          max={TITLE_GEN_MAX_LEN_MAX}
          value={maxLenText}
          disabled={!titleGenEnabled}
          onChange={(e) => setMaxLenText(e.target.value)}
          onBlur={commitMaxLen}
          onKeyDown={(e) => {
            if (e.key === "Enter") commitMaxLen();
          }}
          className="w-24"
        />
      </SettingRow>

      <SettingRow title={t("settings.titleGen.promptTitle")} desc={t("settings.titleGen.promptDesc")}>
        <div className="flex w-full flex-col items-end gap-1.5">
          <textarea
            value={stylePrompt}
            disabled={!titleGenEnabled}
            onChange={(e) => setStylePrompt(e.target.value)}
            onBlur={(e) => commitStyle(e.target.value)}
            placeholder={t("settings.titleGen.promptPlaceholder")}
            rows={3}
            maxLength={2000}
            className={cn(
              "w-full min-w-[16rem] resize-y rounded-md border border-edge bg-surface px-2 py-1.5 text-[0.8571em] text-content outline-none focus:border-accent",
              !titleGenEnabled && "cursor-not-allowed opacity-50",
            )}
          />
          {stylePrompt.length > 0 && (
            <button
              type="button"
              disabled={!titleGenEnabled}
              onClick={() => {
                setStylePrompt("");
                commitStyle("");
              }}
              className="text-[0.7857em] text-content-subtle hover:text-content"
            >
              {t("settings.titleGen.promptReset")}
            </button>
          )}
        </div>
      </SettingRow>
    </SettingsSection>
  );
}
