import type { IpcMain } from "electron";
import { IPC } from "@contracts/ipc";
import { registerModuleHandlers } from "../../src/main/ipc/modules.js";
import { setTestHost } from "./stubs/service.js";
import assert from "node:assert/strict";
import { z } from "zod";
import { ModuleHost } from "../../src/main/modules/ModuleHost.js";
import { ModuleManifestSchema, ResourceSchema, ResultSchema } from "@contracts/modules";
import { mkdtemp, writeFile, rm, symlink, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { fileCapabilities, resolveModuleResource } from "../../src/main/modules/fileCapabilities.js";
import { createModuleClient } from "@contracts/moduleClient";
let passed=0;
const test=async(name:string,fn:()=>unknown)=>{await fn();passed++;console.log("PASS "+name);};
const resource={projectPath:"/project",path:"/project/a.txt"};
const manifest={apiVersion:1,id:"user.demo",version:"1.0.0",title:{zh:"示例",en:"Demo"},permissions:["resource.read"],contributions:[{id:"inspect",slot:"files.context",title:{zh:"检查",en:"Inspect"},capability:"core.file.inspect",view:{title:{zh:"结果",en:"Result"},fields:[{key:"bytes",title:{zh:"大小",en:"Bytes"}}]}}]};
let persisted:unknown;let rejectSave=false;let calls=0;
const host=new ModuleHost({authorize:async(r)=>{if(!r.path.startsWith(r.projectPath+"/"))throw Error("outside root");},persist:async(m)=>{if(rejectSave)throw Error("disk full");persisted=m;}});
host.register({id:"core.file.inspect",kind:"task",input:ResourceSchema,output:ResultSchema,run:async(input,ctx)=>{calls++;ctx.progress(0.5);await new Promise(r=>setTimeout(r,15));return {bytes:input.path.length};}});
const invoke=(requestId:string,path=resource.path)=>host.invoke({moduleId:manifest.id,contributionId:"inspect",resource:{...resource,path},requestId});
const settle=async(id:string)=>{for(let n=0;n<100;n++){const t=host.task({moduleId:manifest.id,taskId:id});if(t.status!=="running")return t;await new Promise(r=>setTimeout(r,5));}throw Error("task did not settle");};
await test("manifest rejects executable fields",()=>assert.throws(()=>ModuleManifestSchema.parse({...manifest,script:"require('fs')"})));
await test("manifest rejects unknown extension slots",()=>assert.throws(()=>ModuleManifestSchema.parse({...manifest,contributions:[{...manifest.contributions[0],slot:"arbitrary.dom"}]})));
await test("duplicate contribution IDs rejected",()=>assert.throws(()=>ModuleManifestSchema.parse({...manifest,contributions:[manifest.contributions[0],manifest.contributions[0]]})));
await test("external module cannot take core namespace",()=>assert.rejects(host.install({...manifest,id:"core.hijack"})));
await test("unknown capability rejected before persistence",()=>assert.rejects(host.install({...manifest,contributions:[{...manifest.contributions[0],capability:"core.shell.exec"}]})));
await test("explicit read permission required",()=>assert.rejects(host.install({...manifest,permissions:[]})));
await test("external declaration is persisted",async()=>{await host.install(manifest);assert.ok(persisted);assert.equal(host.catalog().modules.length,1);});
await test("failed persistence keeps installed definition",async()=>{rejectSave=true;await assert.rejects(host.install({...manifest,version:"2.0.0"}));rejectSave=false;assert.equal(host.catalog().modules[0].version,"1.0.0");});
await test("outside path cannot start task",()=>assert.rejects(invoke("outside","/elsewhere/secret")));
await test("input envelope rejects caller identity injection",()=>assert.rejects(host.invoke({...resource,moduleId:manifest.id,contributionId:"inspect",resource,requestId:"inject",trusted:true})));
let id="";
await test("task starts and returns stable handle",async()=>{const r=await invoke("same");assert.equal(r.type,"task");if(r.type!=="task")throw Error("not task");id=r.task.id;});
await test("same request does not duplicate execution",async()=>{const r=await invoke("same");assert.equal(r.type,"task");if(r.type==="task")assert.equal(r.task.id,id);assert.equal(calls,1);});
await test("same id with different input is rejected",()=>assert.rejects(invoke("same","/project/b.txt")));
await test("task completes with validated output",async()=>{const r=await settle(id);assert.equal(r.status,"completed");assert.equal(r.result?.bytes,resource.path.length);});
await test("same version definition changes invalidate request reuse",async()=>{await host.install({...manifest,title:{zh:"新标题",en:"New title"}});await assert.rejects(invoke("same"));await host.install(manifest);});
await test("snapshots cannot mutate host state",()=>{const t=host.task({moduleId:manifest.id,taskId:id});t.status="failed";assert.equal(host.task({moduleId:manifest.id,taskId:id}).status,"completed");});
await test("task is scoped to originating module",()=>assert.throws(()=>host.task({moduleId:"user.other",taskId:id})));
await test("history is scoped to workspace",()=>{assert.equal(host.tasks({projectPath:"/other"}).length,0);assert.equal(host.tasks({projectPath:"/project"}).length,1);});
await test("cancel wins against late completion",async()=>{const r=await invoke("cancel");if(r.type!=="task")throw Error("not task");host.cancel({moduleId:manifest.id,taskId:r.task.id});await new Promise(r=>setTimeout(r,30));assert.equal(host.task({moduleId:manifest.id,taskId:r.task.id}).status,"cancelled");});
await test("uninstall removes contributions and denies future calls",async()=>{await host.remove(manifest.id);assert.equal(host.catalog().modules.length,0);await assert.rejects(invoke("removed"));});
await test("builtin uses the same registry and invoke path",async()=>{host.addBuiltin({...manifest,id:"core.inspect"});const r=await host.invoke({moduleId:"core.inspect",contributionId:"inspect",resource,requestId:"builtin"});assert.equal(r.type,"task");await assert.rejects(host.remove("core.inspect"));});
await test("duplicate capability cannot replace existing implementation",()=>assert.throws(()=>host.register({id:"core.file.inspect",kind:"task",input:ResourceSchema,output:ResultSchema,run:async()=>({})})));
await test("SDK uses the same host transport",async()=>{const client=createModuleClient({invoke:x=>host.invoke(x),task:async x=>host.task(x),cancel:async x=>host.cancel(x)},"core.inspect");assert.equal((await client.invoke("inspect",resource,"sdk")).type,"task");});
const temp=await mkdtemp(join(tmpdir(),"mcode-module-smoke-"));
try {
  const root=join(temp,"workspace"),outside=join(temp,"outside");await mkdir(root);await mkdir(outside);
  const path=join(root,"test.txt");await writeFile(path,"module platform\n");await writeFile(join(outside,"secret.txt"),"secret");
  const fileHost=new ModuleHost({authorize:async r=>{await resolveModuleResource(r,p=>p===root);},persist:async()=>{}});
  for(const c of fileCapabilities(p=>p===root))fileHost.register(c);
  await fileHost.install(manifest);
  await test("real file capability hashes only the temporary fixture",async()=>{const r=await fileHost.invoke({moduleId:manifest.id,contributionId:"inspect",resource:{projectPath:root,path},requestId:"real"});if(r.type!=="task")throw Error("not task");let task=r.task;while(task.status==="running"){await new Promise(r=>setTimeout(r,5));task=fileHost.task({moduleId:manifest.id,taskId:task.id});}assert.equal(task.status,"completed");assert.equal(task.result?.sha256,createHash("sha256").update("module platform\n").digest("hex"));});
  await test("real path traversal is rejected",()=>assert.rejects(resolveModuleResource({projectPath:root,path:join(outside,"secret.txt")},p=>p===root)));
  await test("unknown root is rejected",()=>assert.rejects(resolveModuleResource({projectPath:outside,path:join(outside,"secret.txt")},p=>p===root)));
  await test("directory cannot be read as file",()=>assert.rejects(resolveModuleResource({projectPath:root,path:root},p=>p===root)));
  await symlink(outside,join(root,"escape"),process.platform==="win32"?"junction":"dir");
  await test("symlink/junction escape is rejected",()=>assert.rejects(resolveModuleResource({projectPath:root,path:join(root,"escape","secret.txt")},p=>p===root)));
  await test("query capability returns immediate validated result",async()=>{await fileHost.install({...manifest,contributions:[{...manifest.contributions[0],capability:"core.file.info"}]});const r=await fileHost.invoke({moduleId:manifest.id,contributionId:"inspect",resource:{projectPath:root,path},requestId:"query"});assert.equal(r.type,"result");});
}finally{await rm(temp,{recursive:true,force:true});}
setTestHost(host);
const ipcHandlers=new Map<string,(event:never,raw:unknown)=>unknown>();
const ipcStub:Pick<IpcMain,"handle">={handle(channel,handler){ipcHandlers.set(channel,handler);}};
registerModuleHandlers(ipcStub as IpcMain);
await test("all seven IPC routes registered",()=>assert.equal(ipcHandlers.size,7));
await test("IPC install rejects absent explicit consent",()=>assert.rejects(Promise.resolve(ipcHandlers.get(IPC.MODULE_INSTALL)!({} as never,{manifest}))));
await test("IPC invoke rejects unknown caller fields",()=>assert.rejects(Promise.resolve(ipcHandlers.get(IPC.MODULE_INVOKE)!({} as never,{moduleId:"core.inspect",contributionId:"inspect",resource,requestId:"badipc",trusted:true}))));
await test("IPC catalog calls the same host",async()=>{const catalog=await ipcHandlers.get(IPC.MODULE_CATALOG)!({} as never,undefined);assert.deepEqual(catalog,host.catalog());});
await new Promise(r=>setTimeout(r,30));console.log(`${passed} checks passed`);
