import { dirname,join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {writeFileSync} from 'node:fs';
import {withAuditPage} from './browser.mjs';
const here=dirname(fileURLToPath(import.meta.url));const checks=[];
const check=(name,pass,detail)=>{checks.push({name,pass,detail});console.log(`${pass?'PASS':'FAIL'} ${name}${detail===undefined?'':' '+JSON.stringify(detail)}`);};
await withAuditPage(here,async page=>{try{
 await page.goto('','window.__ready && document.querySelector("[data-testid=init-manager]")');
 const button=(text,scope='document')=>`[...${scope}.querySelectorAll('button')].find(e=>e.textContent.trim()===${JSON.stringify(text)})`;
 const click=async expr=>{await page.eval(`(${expr}).click()`);await page.sleep(80);};
 const fill=async(label,text)=>{await page.eval(`(()=>{const e=document.querySelector('[aria-label='+${JSON.stringify(JSON.stringify(label))}+']');if(!e)throw Error('Missing control '+${JSON.stringify(label)});const p=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(p,'value').set.call(e,${JSON.stringify(text)});e.dispatchEvent(new Event('input',{bubbles:true}));})()`);await page.sleep(50);};
 check('reserved parser consumes unknown and argument-bearing commands',await page.eval('__parse("/init-missing")?.valid && !__parse("/init-学术 extra")?.valid && __parse("/init")===null && __parse("ordinary text")===null'));
 await fill('Command name','学术');await click(button('Add file'));await fill('Relative file path, e.g. notes/README.md','notes/start.md');await fill('Content','# Initial content');
 await click(button('Add project memory'));await fill('Memory filename, e.g. rules.md','init.md');
 // New UI uses an explicit memory title; the initial implementation reused dialog wording.
 await fill('Memory title','Rules');
 await page.eval(`__setManager(false)`);await page.sleep(100);await page.eval(`__setManager(true)`);await page.waitFor('document.querySelector("[data-testid=init-manager]")');
 check('settings remount retains unsaved draft and file body',await page.eval(`document.querySelector('[aria-label="Command name"]').value==='学术' && document.querySelector('[aria-label="Content"]').value==='# Initial content'`));
 await page.eval('__audit.delayedSave=true');await click(button('Save'));await page.waitFor('__audit.pending.length===1');
 await page.eval('__setManager(false)');await page.sleep(100);await page.eval('__setManager(true)');await page.waitFor('document.querySelector("[data-testid=init-manager]")');
 check('save lock survives settings remount',await page.eval('document.querySelector("[data-testid=init-manager] fieldset").disabled'));
 await page.eval('__audit.pending.shift()();__audit.delayedSave=false');await page.waitFor('__audit.templates.length===1 && __commands.length===1');
 await page.sleep(120);
 check('late save acknowledgement updates remounted editor identity',await page.eval('document.querySelector("[data-testid=init-manager] select").value===__audit.templates[0].id'));

 check('saved template becomes deterministic slash command',await page.eval('__commands[0].name==="init-学术" && __commands[0].kind==="project-init" && __audit.calls.filter(c=>c.method==="save").length===1'));
 await page.eval('__setManager(false);__setPicker(true)');await page.waitFor('document.body.textContent.includes("/init-学术")');
 check('real slash picker exposes saved initializer',await page.eval('document.body.textContent.includes("/init-学术")'));
 await page.eval('__setPicker(false);__setText("/init-学术");__setBusy(true)');await page.sleep(100);await click('document.querySelector("#send")');
 check('busy command is rejected, never queued or sent to model',await page.eval('__audit.toasts.length===1 && __audit.previews.length===0 && !__audit.calls.some(c=>c.method==="model")'));
 await page.eval('__setBusy(false);__setText("/init-学术 extra")');await page.sleep(80);await click('document.querySelector("#send")');
 check('arguments are rejected without model fallback',await page.eval('__audit.toasts.length===2 && __audit.previews.length===0'));
 await page.eval('__setText("/init-学术");__setAttached(true)');await page.sleep(80);await click('document.querySelector("#send")');
 check('attachments are rejected without model fallback',await page.eval('__audit.toasts.length===3 && __audit.previews.length===0'));
 await page.eval('__setAttached(false)');await page.sleep(80);await click('document.querySelector("#send")');await page.waitFor('document.querySelector("[data-testid=init-preview]") && document.body.textContent.includes("C:/isolated/project")');
 check('preview does not apply and shows real project scope',await page.eval('__audit.applies.length===0 && document.body.textContent.includes("Project memory scope: p1")'));
 await click(button('Cancel'));await page.waitFor('!document.querySelector("[data-testid=init-preview]")');
 check('cancel preserves manually typed command',await page.eval('document.querySelector("#chat").value==="/init-学术"'));
 await click('document.querySelector("#send")');await page.waitFor(`${button('Initialize')} && !${button('Initialize')}.disabled`);await page.eval('__setSession("s2")');await page.sleep(80);
 check('switching conversation disables old approval',await page.eval(`${button('Initialize')}.disabled && __audit.applies.length===0`));
 await click(button('Cancel'));await page.eval('__setSession("s1")');await page.sleep(80);await click('document.querySelector("#send")');await page.waitFor(`${button('Initialize')} && !${button('Initialize')}.disabled`);
 await page.eval('__audit.failApply=true');await click(button('Initialize'));await page.waitFor('document.body.textContent.includes("STALE_PREVIEW")');
 check('backend rejection is visible and draft survives',await page.eval('document.querySelector("#chat").value==="/init-学术"'));
 await page.eval('__audit.failApply=false;__setText("Newer draft")');await page.sleep(80);await click(button('Initialize'));await page.waitFor('document.body.textContent.includes("Initialization complete")');
 check('successful initialization never clears a newer draft',await page.eval('document.querySelector("#chat").value==="Newer draft" && __audit.applies.at(-1).sessionId==="s1"'));
 await page.screenshot('project-init-result.png');await click(button('Close'));await page.eval('__setText("/init-学术")');await page.sleep(80);await click('document.querySelector("#send")');await page.waitFor(`${button('Initialize')} && !${button('Initialize')}.disabled`);await click(button('Initialize'));await page.waitFor('document.body.textContent.includes("Initialization complete")');
 check('successful initialization clears unchanged command only',await page.eval('document.querySelector("#chat").value===""'));await click(button('Close'));
 await page.eval('__setText("/init-missing")');await page.sleep(80);await click('document.querySelector("#send")');await page.waitFor('document.body.textContent.includes("UNKNOWN_COMMAND")');
 check('unknown reserved command fails visibly without a model call',await page.eval('!__audit.calls.some(c=>c.method==="model")'));await click(button('Cancel'));
 await page.eval('__setManager(true)');await page.waitFor('document.querySelector("[data-testid=init-manager]")');
 await page.eval(`__audit.templates.push({...structuredClone(__audit.templates[0]),id:'template-b',name:'Other'});window.dispatchEvent(new Event('mcode:project-initializers-changed'));__audit.delayed=true`);
 await page.waitFor('document.querySelectorAll("[data-testid=init-manager] select option").length>=3');
 const select=async value=>{await page.eval(`(()=>{const e=document.querySelector('[data-testid=init-manager] select');e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);await page.sleep(80);};
 const firstId=await page.eval('__audit.templates[0].id');await select('template-b');await page.waitFor('__audit.pending.length===1');await select(firstId);
 await page.eval('__audit.pending.shift()();__audit.delayed=false');await page.sleep(120);
 check('late template read cannot replace a newer selection',await page.eval(`document.querySelector('[aria-label="Command name"]').value==="学术"`));
 await page.eval('__audit.templates=__audit.templates.filter(t=>t.id!=="template-b");window.dispatchEvent(new Event("mcode:project-initializers-changed"))');await page.waitFor('__commands.length===1');
 await fill('Command name','讨论');await click(button('Save'));await page.waitFor('__commands[0]?.name==="init-讨论"');
 check('renaming updates the slash command instead of duplicating it',await page.eval('__commands.length===1 && __audit.templates.length===1'));
 await page.screenshot('project-init-settings.png');
 await click(`[...document.querySelectorAll('[data-testid=init-manager] button')].filter(e=>e.textContent.trim()==='Delete').at(-1)`);await page.waitFor('document.querySelector("[role=alertdialog], [role=dialog]")');
 await click(button('Delete','document.querySelector("[role=alertdialog], [role=dialog]")'));await page.waitFor('__audit.templates.length===0 && __commands.length===0');
 check('delete removes template and slash entry without file deletion calls',await page.eval('__audit.calls.some(c=>c.method==="delete") && !__audit.calls.some(c=>c.method==="deleteFile")'));
 await page.goto('mobile','window.__ready && document.querySelector("#host")');
 await page.eval('__setPicker(true)');await page.sleep(250);
 check('mobile ordinary slash opening never requests desktop initializer list',await page.eval('__audit.calls.filter(c=>c.method==="list").length===0'));
 check('mobile ordinary slash opening produces no unsupported error toast',await page.eval('__audit.toasts.length===0'));
 await page.eval('__setPicker(false);__audit.toasts.length=0;__setText("/init-学术")');await page.sleep(80);await click('document.querySelector("#send")');
 check('mobile reserved command is explicitly rejected without model or preview',await page.eval('__audit.toasts.length===1 && __audit.previews.length===0 && !__audit.calls.some(c=>c.method==="model")'));
 check('no uncaught browser exceptions',page.exceptions.length===0,page.exceptions);
 }catch(error){check('browser scenario completed',false,error.stack);await page.screenshot('failure.png');}});
writeFileSync(join(here,'result.json'),JSON.stringify(checks,null,2));console.log(`Project init UI smoke: ${checks.filter(c=>c.pass).length}/${checks.length}`);if(checks.some(c=>!c.pass))process.exitCode=1;
